language: cpp
sudo: required
notifications:
  email: false

services:
- docker

arch:
  repos:
  #- papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
  # pacman packages
  - g++
  - cmake
  - git
  - ninja
  - gtest
  - glm
  - intel-tbb
  - embree
  - assimp
  # aur packages
  - microsoft-gsl-git
  # packages from papyros repo
  #- papyros-shell
  script:
  - "./travis_build_script.sh"

script:
- "sudo apt install python3"
- "sudo apt install python3-pip"
- "pip3 install pyyaml"
- export CC=${CC}
- export CXX=${CXX}
- export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
- "sudo python3 travis.py"
#- "sudo chmod +x arch-travis"