dist: trusty
sudo: false
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
 - export CC=/usr/bin/gcc-7
 - export CXX=/usr/bin/g++-7
 - cmake .
 - cmake --build . -- -j2