language: cpp
sudo: required

services:
- docker

arch:
  repos:
  #- papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
  # pacman packages
  - g++
  - cmake
  - git
  - ninja
  - gtest
  - glm
  - intel-tbb
  - embree
  - assimp
  # aur packages
  - microsoft-gsl-git
  # packages from papyros repo
  #- papyros-shell
  script:
  - "./travis_build_script.sh"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"