language: cpp
sudo: required
notifications:
  email: false

services:
- docker

arch:
  repos:
  #- papyros=http://dash.papyros.io/repos/$repo/$arch

  packages:
  # pacman packages
  - g++
  - cmake
  - git
  - ninja
  - gtest
  - glm
  - intel-tbb
  - embree
  - assimp
  - openimageio
  - flatbuffers
  - boost
  # Required by openimageio but for some reason not marked as dependency
  - freetype2

  # aur packages
  - microsoft-gsl-git

  # packages from papyros repo
  #- papyros-shell
  script:
  - "./travis/build_in_arch.sh"

script:
- sudo apt install python3
- sudo apt install python3-pip
- sudo pip3 install pyyaml
- export CC=${CC}
- export CXX=${CXX}
- export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
- chmod +x "${TRAVIS_BUILD_DIR}/travis/build_in_arch.sh"
- python3 ./travis/run_arch_docker.py
#- "sudo chmod +x arch-travis"
